name: fullstack
description: Dart Frog application built for STRV meetup
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  dotenv: ^4.2.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  postgres: ^3.4.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
